services:
  - type: web
    name: dev-deakin-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
